/*
 * File: app/view/${entity.name}List.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('${app.name}.view.${entity.name}List', {
    extend: 'Ext.dataview.List',
    alias: 'widget.${entity.lowerCase}List',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        itemId: '${entity.lowerCase}List',
        store: '${entity.name}JsonPStore',
        onItemDisclosure: true,
        itemTpl: [
            '<div>{[values[Object.keys(values)[0]]]}</div>'
        ]
    }

});
