/*
 * File: app/view/${entity.name}NavigationView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('${app.name}.view.${entity.name}NavigationView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.${entity.lowerCase}NavigationView',

    requires: [
        '${app.name}.view.${entity.name}List',
        'Ext.navigation.Bar',
        'Ext.Button',
        'Ext.dataview.List'
    ],

    config: {
        itemId: '${entity.lowerCase}NavigationView',
        navigationBar: {
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    itemId: '${entity.lowerCase}RefreshButton',
                    iconCls: 'refresh',
                    text: ''
                },
                {
                    xtype: 'button',
                    align: 'right',
                    itemId: '${entity.lowerCase}AddButton',
                    iconCls: 'add'
                }
            ]
        },
        items: [
            {
                xtype: '${entity.lowerCase}List'
            }
        ]
    }

});
